### PR TITLE
Create szeitlin.github.io.json

### PR DESCRIPTION
**Pull request by szeitlin**
adding my blog and some links to social. Let me know if you want me to delete the ones that are blank or what I should do there.

### CODE REVIEW

**Comment by cosimameyer** [comment]
@szeitlin thanks so much for contributing! 😊 

Yes, you're right - you'd need to remove the non-filled rows (so for instance `subtitle": "subtitle or tagline", //optional` should be removed. 

I also think the image URL should be `https://girlgeek.io/wp-content/uploads/2020/09/sentry-girl-geek-samantha-g-zeitlin.png` (otherwise it won’t be accessible). 

I'm not sure but when checking with [simple pie](https://simplepie.org/demo/) it doesn't seem to be able to find your RSS feed. RSS feeds are sometimes tricky and I learnt something about different themes along the way - they are collected [here](https://github.com/cosimameyer/awesome-pyladies-blogs/blob/main/CONTRIBUTING.md#rss-feed). I think it might be this [Hugo theme](https://github.com/theNewDynamic/gohugo-theme-ananke), so some of the suggestions might be helpful 🙂 Also, with Hugo it’s usually possible to set up categories (or tags, which can be then used for specific RSS feeds). It’d be amazing to have this for your blog feed as well to keep the bot sorted 🙂

Everything else looks great! Thanks so much for taking your time to contribute 🙂

**Comment by szeitlin** [comment]
hm. I fixed the json file, and the RSS feed seems fine when I check it. Here's a screenshot of how it looks on simple pie (thanks for that tip btw):
Screen Shot 2023-04-26 at 3 27 16 PM

**Comment by cosimameyer** [comment]
Thanks so much for revising! ☺️ 
I tested the RSS feed and it needs to be `https://szeitlin.github.io/index.xml` (so the `https://` is missing) - if you could change this, I'm very happy to merge it.

**Comment by szeitlin** [comment]
updated! Thanks for catching that.

**Review by cosimameyer — APPROVED** [review]

**Comment by cosimameyer** [comment]
Thanks so much for contributing 🎉

**Pull request merged**
